name: Dependency Vulnerability Scan
on:
  push:
    branches: [ develop, issue-* ]
    tags: [ v* ]
  pull_request:
    branches: [ develop, main ]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}